name: Build and release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: macos-14

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Install dependencies
        run: |
          brew update
          brew install bison flex libyaml openssl pkgconfig || true

      - name: Install cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "3.31.6"

      - name: Build Fluent Bit packages
        run: |
          export LIBRARY_PATH=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib:$LIBRARY_PATH
          cmake -DCPACK_GENERATOR=productbuild -DFLB_NIGHTLY_BUILD=false ../ -DOPENSSL_ROOT_DIR=$(brew --prefix openssl)
          cmake --build .
        working-directory: build

      - name: Bundle libyaml.dylib and fix install name
        run: |
          # Find and copy libyaml.dylib
          YAML_PATH=$(brew --prefix libyaml)/lib/libyaml.dylib
          mkdir -p build/Frameworks
          cp "$YAML_PATH" build/Frameworks/

          # Determine your built binary's name – update if different!
          BIN=build/fluent-bit

          # Patch the binary so it loads the bundled libyaml
          install_name_tool -change "$YAML_PATH" "@executable_path/../Frameworks/libyaml.dylib" "$BIN"

          # Optionally codesign
          codesign --sign - build/Frameworks/libyaml.dylib

        shell: bash

      - name: Build pkg with cpack
        run: cpack -G productbuild
        working-directory: build

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: build/fluent-bit-*-apple*
          tag_name: 'test'
