name: Sync master with upstream

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Fetch and sync upstream changes
        env:
          UPSTREAM_REPO: fluent/fluent-bit
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh repo sync ${UPSTREAM_REPO} --branch master
          git push origin master
